import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script";
import XRGuard from "../components/XRGuard";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <head>
          {/* 8th Wall Engine Binary (SLAM) */}
          <Script 
            src="https://cdn.jsdelivr.net/npm/@8thwall/engine-binary@1/dist/xr.js"
            strategy="beforeInteractive"
            crossOrigin="anonymous"
            data-preload-chunks="slam"
          />
          {/* 8th Wall XR Extras */}
          <Script 
            src="https://cdn.jsdelivr.net/npm/@8thwall/xrextras@1/dist/xrextras.js"
            strategy="beforeInteractive"
            crossOrigin="anonymous"
          />
          {/* 8th Wall Landing Page */}
          <Script 
            src="https://cdn.jsdelivr.net/npm/@8thwall/landing-page@1/dist/landing-page.js"
            strategy="beforeInteractive"
            crossOrigin="anonymous"
          />
        </head>
        <body className="min-h-full flex flex-col">
          <XRGuard />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
